#### **Task 1: Perform Mathematical Operations on NumPy Arrays**

In [ ]:
%pip install numpy

1. Create two 1D arrays of size 5 with random integers between 1 and 10.

In [7]:
# Write your answer from this cell onwards
import numpy as np
arr1=np.array(np.random.randint(1,10,size=5))
print("arr1:",arr1)
arr2=np.array(np.random.randint(1,10,size=5))
print("arr2:",arr2)


arr1: [3 6 1 5 1]
arr2: [6 7 7 8 6]


2. Perform the following mathematical operations on these arrays:
   - Element-wise addition
   - Element-wise subtraction
   - Element-wise multiplication
   - Element-wise division

In [8]:
# Write your answer from this cell onwards
sum=arr1+arr2
print("sum:",sum)
sub=arr1-arr2
print("sub:",sub)
mul=arr1*arr2
print("mul:",mul)
dev=arr1/arr2
print("dev:",dev)

sum: [ 9 13  8 13  7]
sub: [-3 -1 -6 -3 -5]
mul: [18 42  7 40  6]
dev: [0.5        0.85714286 0.14285714 0.625      0.16666667]


3. Compute the dot product of the two arrays.

In [9]:
# Write your answer from this cell onwards
product=np.dot(arr1,arr2)
print(product)

113


#### **Task 2: Combine and Split Arrays**

1. Create two 2D arrays of shape (3, 3) with random integers between 1 and 20.

In [20]:
# Write your answer from this cell onwards
import numpy as np
arr1=np.array(np.random.randint(1,20,size=9)).reshape(3,3)
print("arr1:\n",arr1)
arr2=np.array(np.random.randint(1,20,size=9)).reshape(3,3)
print("arr2:\n",arr2)

concate=np.concatenate((arr1,arr2),axis=0)
print("concatenate axis=0:-\n",concate)

concate=np.concatenate((arr1,arr2),axis=1)
print("concatenate axis=1:-\n",concate)

arr1:
 [[ 2 15 14]
 [16  2 12]
 [14  7  5]]
arr2:
 [[19  2  1]
 [16 11  4]
 [18 15  2]]
concatenate axis=0:-
 [[ 2 15 14]
 [16  2 12]
 [14  7  5]
 [19  2  1]
 [16 11  4]
 [18 15  2]]
concatenate axis=1:-
 [[ 2 15 14 19  2  1]
 [16  2 12 16 11  4]
 [14  7  5 18 15  2]]


2. Combine these arrays:
   - Vertically using `vstack`
   - Horizontally using `hstack`

In [27]:
# Write your answer from this cell onwards
verticaly=np.vstack((arr1,arr2))
print("concatenate vstack:-\n",verticaly)

horizontal=np.hstack((arr1,arr2))
print("concatenate hstack:-\n",horizontal)

concatenate vstack:-
 [[ 2 15 14]
 [16  2 12]
 [14  7  5]
 [19  2  1]
 [16 11  4]
 [18 15  2]]
concatenate hstack:-
 [[ 2 15 14 19  2  1]
 [16  2 12 16 11  4]
 [14  7  5 18 15  2]]


3. Split the combined array back into the original two arrays using `vsplit` and `hsplit`.

In [34]:
# Write your answer from this cell onwards
verticalysplit=np.vsplit(verticaly,2)
print("concatenate vstack:-\n")
for x in verticalysplit:
    print(x)

horizontalsplit=np.hstack(horizontal)
print("concatenate horizontal split:-\n",horizontalsplit)

concatenate vstack:-

[[ 2 15 14]
 [16  2 12]
 [14  7  5]]
[[19  2  1]
 [16 11  4]
 [18 15  2]]
concatenate horizontal split:-
 [ 2 15 14 19  2  1 16  2 12 16 11  4 14  7  5 18 15  2]


#### **Task 3: Search, Sort, and Filter in Arrays**

1. Create a 1D array with 10 random integers between 1 and 50.

In [44]:
# Write your answer from this cell onwards

import numpy as np
arr1=np.array(np.random.randint(1,50,size=10))
print("arr1:",arr1)

arr1: [18  2 16  3 18 43  1 22 45 28]


2. Find the indices of elements that are greater than 25.

In [45]:
# Write your answer from this cell onwards
print(np.where(arr1>25))
print(arr1[arr1>25])

(array([5, 8, 9]),)
[43 45 28]


3. Sort the array in ascending order.

In [48]:
# Write your answer from this cell onwards
print(np.sort(arr1))
print(np.sort(arr1)[::-1])


[ 1  2  3 16 18 18 22 28 43 45]
[45 43 28 22 18 18 16  3  2  1]


4. Filter the array to include only even numbers.

In [49]:
# Write your answer from this cell onwards
print(arr1[arr1%2==0])

[18  2 16 18 22 28]


#### **Task 4: Aggregate Functions**

1. Create a 2D array of shape (4, 5) with random integers between 10 and 100.

In [50]:
# Write your answer from this cell onwards
import numpy as np
arr1=np.array(np.random.randint(10,100,size=20)).reshape(4,5)
print("arr1:\n",arr1)

arr1:
 [[23 35 57 30 25]
 [41 78 28 66 83]
 [98 44 58 62 81]
 [42 63 50 56 76]]


2. Perform the following aggregate operations:
   - Compute the sum of all elements.
   - Find the maximum and minimum values in the array.
   - Compute the mean and standard deviation of the elements.
   - Find the sum of elements along each row and each column.

In [62]:
# Write your answer from this cell onwards
print("sum:",np.sum(arr1))
print("max:",np.max(arr1))
print("min:",np.min(arr1))
print("mean:",np.mean(arr1))
print("std:",np.std(arr1))
print("row sum:",np.sum(arr1,axis=1))
print("col sum:",np.sum(arr1,axis=0))

sum: 1096
max: 98
min: 23
mean: 54.8
std: 20.87486526902629
row sum: [170 296 343 287]
col sum: [204 220 193 214 265]


#### **Task 5: Statistical Functions**

1. Create a 2D array of shape (5, 5) with random integers between 1 and 50.

In [63]:
# Write your answer from this cell onwards
import numpy as np
arr1=np.array(np.random.randint(1,50,size=25)).reshape(5,5)
print("arr1:\n",arr1)

arr1:
 [[48 28  6 17 46]
 [43  5 25 11 24]
 [31  5 19 28 37]
 [ 9 13 12 17 17]
 [28 27 13 49 26]]


2. Compute the following statistics:
   - Median of all elements.
   - Variance of the elements.
   - Cumulative sum along each row.
   - Cumulative product along each column.

In [65]:
# Write your answer from this cell onwards
print("median:",np.median(arr1))
print("variance:",np.var(arr1))
print("row sum:",np.sum(arr1,axis=1))
print("col sum:",np.prod(arr1,axis=0))

median: 24.0
variance: 172.5504
row sum: [145 108 120  68 143]
col sum: [16123968   245700   444600  4361588 18054816]


#### **Task 6: Combine All Concepts**

1. Create a dataset using a 2D NumPy array with random integers between 1 and 100, where rows represent students and columns represent their scores in 5 subjects.

In [ ]:
# Write your answer from this cell onwards


2. Perform the following:
   - Compute the total score for each student.
   - Find the student with the highest and lowest total score.
   - Sort the array based on total scores.
   - Filter students who scored more than 75 in at least three subjects.

In [ ]:
# Write your answer from this cell onwards
