#### **1. Introduction to NumPy**

**Task 1**: Import the NumPy library and print its version.

In [3]:
# Write your answer from this cell onwards

import numpy as np
np.__version__


'2.2.3'

**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [4]:
# Write your answer from this cell onwards

np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [5]:
# Write your answer from this cell onwards

Array=np.random.rand(8,2).astype(float)

print(Array,"\n")
print("Array_Shape:",Array.shape)
print("Array_Type:",Array.dtype)

[[0.97451642 0.48074779]
 [0.09004164 0.43992349]
 [0.75053971 0.7357985 ]
 [0.44309775 0.75235024]
 [0.4148618  0.44416487]
 [0.70148194 0.2480013 ]
 [0.94240021 0.22574701]
 [0.06497274 0.9825    ]] 

Array_Shape: (8, 2)
Array_Type: float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [2]:
# Write your answer from this cell onwards
import numpy as np
array=np.linspace(0,11,50,dtype=int)
print(array)

[ 0  0  0  0  0  1  1  1  1  2  2  2  2  2  3  3  3  3  4  4  4  4  4  5
  5  5  5  6  6  6  6  6  7  7  7  7  8  8  8  8  8  9  9  9  9 10 10 10
 10 11]


**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [17]:
# Write your answer from this cell onwards

arr1=[1,2,3,4,5,6,7,8,9,10]
arr2=[1,2,3,4,5,6,7,8,9,10]

arr3=arr1+arr2
print(arr3)

a1=np.arange(10)
a2=np.arange(10,20)

a3=a1+a2
print(a3)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10 12 14 16 18 20 22 24 26 28]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [47]:
# Write your answer from this cell onwards

import numpy as np
arr=np.zeros((3,4),dtype=np.int32)
print(arr)

print(np.shape(arr))
print(arr.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
int32


**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [49]:
# Write your answer from this cell onwards
import numpy as np
arr=np.ones((2,5),dtype=float)
print(arr)

print(np.shape(arr))
print(arr.dtype)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
float64


**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [30]:
# Write your answer from this cell onwards

arr=np.arange(10,50,5)
print(arr)


[10 15 20 25 30 35 40 45]


**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [55]:
# Write your answer from this cell onwards
import numpy as np

arr=np.arange(27).reshape(3,3,3)
print(arr)
arr.ndim

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


3

**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [54]:
# Write your answer from this cell onwards

import numpy as np

array =np.random.randint(1,21,size=(4,4))
print(array)

array.ndim



[[ 3  4  9  9]
 [ 8 19 14  3]
 [17 20 15 15]
 [14  9  4  6]]


2

---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [13]:
# Write your answer from this cell onwards


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [14]:
# Write your answer from this cell onwards


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [15]:
# Write your answer from this cell onwards


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [16]:
# Write your answer from this cell onwards


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [17]:
# Write your answer from this cell onwards
