In [ ]:
# Numpy Analyzer #
#================#

#link - https://docs.google.com/document/d/1xpbevjo2WA8yQ8BcJkKiHYZSPm5sDWkmIuA2kDAptE8/edit?tab=t.0

# Import libraries
import numpy as np

# class Besic_information:
#     while True:
#         print("===============================================")
#         print("  ***   Chose an option:")
#         print("-----------------------------------------------")
#         print("   1. Perform Methemetical Operations")                        #OPSTIONS
#         print("   2. Combine Or Split Arrays")
#         print("   3. Search , Sort Or Filter Arrays")
#         print("   4. Compute Aggrigate and Statistics")
#         print("   5. Go back")
#         print("===============================================\n")

#         array_choise=int(input("Enter Your Choise:"))
#         match array_choise:
#             case 1:
#                 pass
                
#             case 2:
#                 pass
                
#             case 5:
#                 break

    


print("\n=========================")
print(" Welcome To Numpy Analyzer")
print("==========================")
while True:     #LOOP CONTINUE WHILE TRUE

    print("\n==============================================")
    print("  ***   Select the type of array to create:")
    print("   1. 1D Array")
    print("   2. 2D Array")
    print("   3. 3D Array")
    print("   4. Exit")

    main_choise=int(input("Enter your choise:"))

    match main_choise:      #SWITCH CASE FOR MATCH CHOISES
    
    #CASE 1 FOR FILE SYSTEM OPERATIONS
        case 1:
            len=int(input("Enter your len for 1D array: "))
            onearr=np.array(list(map(int,(input(f"Enter {len} Elements for 1d Array(Space separeted):").split()))))
            print("1D Array created Successfully:\n",onearr)
            while True:
                print("===============================================")
                print("  ***   Chose an option:")
                print("-----------------------------------------------")
                print("   1. Perform Methemetical Operations")                        #OPSTIONS
                print("   1. Perform Methemetical Operations")                        #OPSTIONS
                print("   2. Combine Or Split Arrays")
                print("   3. Search , Sort Or Filter Arrays")
                print("   4. Compute Aggrigate and Statistics")
                print("   5. Go back")
                print("===============================================\n")

                array_choise=int(input("Enter Your Choise:"))
                match array_choise:
                    case 1:
                        pass
                        
                    case 2:
                        pass
                        
                    case 5:
                        break
                    
        case 2:
            row=int(input("Enter the number of rows: "))
            col=int(input("Enter the number of columns: "))
            elements=np.array(list(map(int,(input(f"Enter {row*col} Elements for 2d Array(Space separeted):").split()))))
            twoarr=elements.reshape(row,col)
            print("2D Array created Successfully:\n",twoarr)
            while True:
                print("===============================================")
                print("  ***   Chose an option:")
                print("-----------------------------------------------")
                print("   1. Perform Methemetical Operations")                        #OPSTIONS
                print("   2. Combine Or Split Arrays")
                print("   3. Search , Sort Or Filter Arrays")
                print("   4. Compute Aggrigate and Statistics")
                print("   5. Go back")
                print("===============================================\n")

                array_choise=int(input("Enter Your Choise:"))
                match array_choise:
                    case 1:
                       pass
                        
                    case 2:
                        pass
                        
                    case 5:
                        
                        break
        case 3:
            row=int(input("Enter the number of rows: "))
            col=int(input("Enter the number of columns: "))
            depth=int(input("Enter the number of depth: "))
            elements=np.array(list(map(int,(input(f"Enter {row*col*depth} Elements for 3d Array(Space separeted):").split()))))
            threearr=elements.reshape(row,col,depth)
            print("3D Array created Successfully:\n",threearr)
            while True:
                print("===============================================")
                print("  ***   Chose an option:")
                print("-----------------------------------------------")
                print("   1. Perform Methemetical Operations")                        #OPSTIONS
                print("   2. Combine Or Split Arrays")
                print("   3. Search , Sort Or Filter Arrays")
                print("   4. Compute Aggrigate and Statistics")
                print("   5. Go back")
                print("===============================================\n")

                array_choise=int(input("Enter Your Choise:"))
                match array_choise:
                    case 1:
                        pass
                        
                    case 2:
                        pass
                        
                    case 3:
                        pass
   
    #CASE 6 FOR BREAK
        case 4:
            print("Exiting programm...")
            break


 Welcome To Numpy Analyzer

  ***   Select the type of array to create:
   1. 1D Array
   2. 2D Array
   3. 3D Array
   4. Exit
1D Array created Successfully:
 [1 2 3 4 5 6 7 8]
  ***   Chose an option:
-----------------------------------------------
   1. Perform Methemetical Operations
   2. Combine Or Split Arrays
   3. Search , Sort Or Filter Arrays
   4. Compute Aggrigate and Statistics
   5. Go back


  ***   Select the type of array to create:
   1. 1D Array
   2. 2D Array
   3. 3D Array
   4. Exit
Exiting programm...


In [1]:
import numpy as np

class ArraySearch:
    def __init__(self, arr):
        self.arr = arr

    def Search(self):
        print("Original array:\n", self.arr)
        value = int(input("Enter value for searching: "))
        result = np.where(self.arr == value)
        if result[0].size > 0:
            print(f"Value {value} found at indices: {result}")
        else:
            print(f"Value {value} not found in the array.")

# Example usage for 1D array:
arr_1d = np.array([10, 20, 30, 40, 50])
search_instance_1d = ArraySearch(arr_1d)
search_instance_1d.Search()

# Example usage for 2D array:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
search_instance_2d = ArraySearch(arr_2d)
search_instance_2d.Search()

# Example usage for 3D array:
arr_3d = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])
search_instance_3d = ArraySearch(arr_3d)
search_instance_3d.Search()


Original array:
 [10 20 30 40 50]
Value 20 found at indices: (array([1]),)
Original array:
 [[10 20 30]
 [40 50 60]]
Value 50 found at indices: (array([1]), array([1]))
Original array:
 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
Value 70 found at indices: (array([1]), array([1]), array([0]))
