In [ ]:
%pip install numpy

In [11]:
import numpy as np

class Indexing_Slicing:
    def oneDarray(self):
        while True:
            print("\n Chose An option:-")
            print("  1. Indexing")
            print("  2. Slicing")
            print("  3. Go back")
            indexchoice=int(input("Enter Your Choise:"))
            
            if indexchoice==1:
                Index=int(input("Enter Index To catch value from 1D array:"))
                print(f"Arry[{Index}] : {arr[Index]}")
                
            elif indexchoice==2:
                start,end=map(int,input("Enter slicing point for 1D array (Start:End):").split(":"))
                print("\nSliced Array:")
                print(f"Arry[{start}:{end}] = {arr[start:end]}")
                
            elif indexchoice==3:    
                break
            
    def twoDarray(self):
        while True:
            print("\n Chose An option:-")
            print("  1. Indexing")
            print("  2. Slicing")
            print("  3. Go back")
            indexchoice=int(input("Enter Your Choise:"))
            
            if indexchoice==1:
                row,col=map(int,input("Enter Index To catch value from 2D array (row,col):").split(","))
                print(f"Arry[{row},{col}] : {arr[row,col]}")
                
            elif indexchoice==2:
                rstart,rend=map(int,input("Enter the row range (Start:End):").split(":"))
                cstart,cend=map(int,input("Enter the column range(Start:End):").split(":"))
                print("\nSliced Array:")
                print(f"{arr[rstart:rend,cstart:cend]}")
                
            elif indexchoice==3:    
                break 
            
    def threedarray(self):
        while True:
            print("\n Chose An option:-")
            print("  1. Indexing")
            print("  2. Slicing")
            print("  3. Go back")
            indexchoice=int(input("Enter Your Choise:"))
            
            if indexchoice==1:
                row,col,dep=map(int,input("Enter Index To catch value from 3D array (row,col,dep):").split(","))
                print(f"Arry[{row},{col},{dep}] : \n{arr[row,col,dep]}")
                
            elif indexchoice==2:
                r_start,r_end=map(int,input("Enter the row range (Start:End):").split(":"))
                c_start,c_end=map(int,input("Enter the column range(Start:End):").split(":"))
                d_start,d_end=map(int,input("Enter the depth range(Start:End):").split(":"))
                print("\nSliced Array:")
                print(f"{arr[r_start:r_end,c_start:c_end,d_start:d_end]}")
                
            elif indexchoice==3:    
                break

class MathematicalOperation:
    def Addition(self):
        total_ele=len(arr)
        arr2=np.array(list(map(int,input(f"Enter {total_ele} elements for addition (space separated):").split())))
        result=arr + arr2
        print("Result of Addition",result)

    def Subtraction(self):
        total_ele=len(arr)
        arr2=np.array(list(map(int,input(f"Enter {total_ele} elements for subtraction (space separated):").split())))
        result=arr - arr2
        print("Result of Subtraction",result)

    def Multiplication(self):
        total_ele=len(arr)
        arr2=np.array(list(map(int,input(f"Enter {total_ele} elements for multiplication (space separated):").split())))
        result=arr * arr2
        print("Result of Multiplication",result)

    def Division(self):
        total_ele=len(arr)
        arr2=np.array(list(map(int,input(f"Enter {total_ele} elements for division (space separated):").split())))
        result=arr / arr2
        print("Result of Division",result)
        
        
class Combine_Split:
    
    def Combine(self):
        if arr.ndim==1:
            total_ele=len(arr)
        elif arr.ndim==2:
            total_ele=arr.shape[0]*arr.shape[1]
        elif arr.ndim==3:   
            total_ele=arr.shape[0]*arr.shape[1]*arr.shape[2]
        else:
            print("Invelid dimention")
        
        arr2=np.array(list(map(int,input(f"Enter {total_ele} elements for combine (space separated):").split())))
        if arr.ndim==1:
            result=np.concatenate((arr,arr2))
        elif arr.ndim == 2:
            arr2_reshaped=arr2.reshape(arr.shape[0], -1)
            result=np.concatenate((arr,arr2_reshaped),axis=1)
        elif arr.ndim==3:
            arr2_reshaped=arr2.reshape(arr.shape[0],arr.shape[1], -1)
            result=np.concatenate((arr,arr2_reshaped),axis=2)
        print("Combined Array:\n",result)
        
    def Split(self):
        if arr.ndim==1:
            split_array=np.array_split(arr,2)
        elif arr.ndim==2:
            split_array=np.hsplit(arr,2)
        elif arr.ndim==3:   
            split_array=np.dsplit(arr,3)
        else:
            print("Invelid dimention")
        print(f"Original array:\n",arr)
        print("Splitted array:")
        for i in split_array:
            print(i)
            
class SearchSortFilter:
    
    def Search(self):
        print("Original array:\n",arr)
        value=int(input("Enter value for searching:"))
        result=np.where(arr==value)
        if result[0]!=0:
            print(f"Value {value} found at : {result}")
        else:
            print(f"Value {value} not found in the array.")

    def Sort(self):
        sorted_array=np.sort(arr)
        print(f"Sorted Array:\n",sorted_array)
            
    def Filter(self):
        filtered_array=arr[arr%2==0]
        print(filtered_array)


obj = Indexing_Slicing()
mth = MathematicalOperation()
cmb = Combine_Split()
fil = SearchSortFilter()

print("\n=========================")
print(" Welcome To Numpy Analyzer")
print("==========================")
while True:     #LOOP CONTINUE WHILE TRUE

    print("===============================================")
    print("  ***   Choose an option:")
    print("-----------------------------------------------")
    print("   1. Create A Numpy Array")
    print("   2. Perform Mathematical Operations")                        #OPTIONS
    print("   3. Combine Or Split Arrays")
    print("   4. Search , Sort Or Filter Arrays")
    print("   5. Compute Aggregate and Statistics")
    print("   6. Exit")
    print("===============================================\n")

    main_choice=int(input("Enter your choice:"))

    match main_choice:      #SWITCH CASE FOR MATCH CHOICES
    
    #CASE 1 FOR FILE SYSTEM OPERATIONS
        case 1:
            while True:
                print("\n==============================================")
                print("  ***   Select the type of array to create:")
                print("   1. 1D Array")
                print("   2. 2D Array")
                print("   3. 3D Array")

                array_choice=int(input("Enter Your Choice:"))
                match array_choice:
                    case 1:
                        length=int(input("Enter the length for 1D array: "))
                        arr=np.array(list(map(int,(input(f"Enter {length} Elements for 1D Array (Space separated):").split()))))
                        print("1D Array created Successfully:\n",arr)
                        
                        obj.oneDarray()
                        break
                        
                    case 2:
                        row=int(input("Enter the number of rows: "))
                        col=int(input("Enter the number of columns: "))
                        elements=np.array(list(map(int,(input(f"Enter {row*col} Elements for 2D Array (Space separated):").split()))))
                        arr=elements.reshape(row,col)
                        print("2D Array created Successfully:\n",arr)
                        
                        obj.twoDarray()
                        break
                        
                        
                    case 3:
                        row=int(input("Enter the number of rows: "))
                        col=int(input("Enter the number of columns: "))
                        depth=int(input("Enter the number of depth: "))
                        elements=np.array(list(map(int,(input(f"Enter {row*col*depth} Elements for 3D Array (Space separated):").split()))))
                        arr=elements.reshape(row,col,depth)
                        print("3D Array created Successfully:\n",arr)
                        
                        obj.threedarray()
                        break
                     
        case 2:
            
            print("\n==============================================")
            print("  ***   Select the mathematical operation:")
            print("==============================================")
            print(" 1. Addition  2. Subtraction  3. Multiplication  4. Division")

            choice=int(input("Enter your choice:"))
            if choice==1:
                mth.Addition()
            elif choice==2:
                mth.Subtraction()
            elif choice==3:
                mth.Multiplication()
            elif choice==4:
                mth.Division()
            else:
                print("Invalid choice...")
                
        case 3:
            
            print("\n==============================================")
            print("  ***   Choose an operation:")
            print("==============================================")
            print(" 1. Combine arrays  2. Split arrays")

            choice=int(input("Enter your choice:"))
            if choice==1:
                cmb.Combine()
            elif choice==2:
                cmb.Split()
            else:
                print("Invalid choice...")
               
        case 4:
            
            print("\n==============================================")
            print("  ***   Choose an operation:")
            print("==============================================")
            print(" 1. Search  2. Sort  3. Filter")

            choice=int(input("Enter your choice:"))
            if choice==1:
                fil.Search()
            elif choice==2:
                fil.Sort()
            elif choice==3:
                fil.Filter()
            else:
                print("Invalid choice...")
                        
    #CASE 6 FOR BREAK
        case 6:
            print("Exiting program...")
            break



 Welcome To Numpy Analyzer
  ***   Choose an option:
-----------------------------------------------
   1. Create A Numpy Array
   2. Perform Mathematical Operations
   3. Combine Or Split Arrays
   4. Search , Sort Or Filter Arrays
   5. Compute Aggregate and Statistics
   6. Exit


  ***   Select the type of array to create:
   1. 1D Array
   2. 2D Array
   3. 3D Array
2D Array created Successfully:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Chose An option:-
  1. Indexing
  2. Slicing
  3. Go back
  ***   Choose an option:
-----------------------------------------------
   1. Create A Numpy Array
   2. Perform Mathematical Operations
   3. Combine Or Split Arrays
   4. Search , Sort Or Filter Arrays
   5. Compute Aggregate and Statistics
   6. Exit


  ***   Choose an operation:
 1. Search  2. Sort  3. Filter
[2 4 6 8]
  ***   Choose an option:
-----------------------------------------------
   1. Create A Numpy Array
   2. Perform Mathematical Operations
   3. Combine Or Split Arrays
   4. Se