In [1]:
import numpy as np

# using loadtxt()
arr = np.loadtxt("subs.csv", delimiter=",", dtype=str)
arr


array(['Subscribers gained', '48', '57', '40', '43', '44', '46', '33',
       '40', '44', '74', '49', '56', '49', '42', '39', '44', '54', '51',
       '40', '37', '40', '45', '50', '56', '35', '49', '46', '88', '61',
       '42', '56', '50', '50', '49', '76', '123', '108', '110', '56',
       '62', '65', '66', '33', '66', '82', '126', '109', '88', '83',
       '108', '101', '128', '111', '96', '101', '99', '105', '72', '93',
       '76', '104', '70', '80', '99', '104', '136', '115', '123', '112',
       '145', '87', '84', '92', '80', '70', '70', '132', '123', '98',
       '96', '88', '86', '92', '92', '110', '120', '105', '72', '84',
       '90', '78', '81', '89', '89', '93', '86', '95', '83', '72', '87',
       '100', '72', '79', '67', '71', '90', '77', '100', '88', '65', '95',
       '78', '89', '96', '81', '105', '80', '66', '73', '68', '159', '90',
       '83', '76', '77', '66', '64', '85', '136', '135', '71', '79', '75',
       '72', '78', '109', '93', '84', '74', '87', '128', '10

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([58, 80, 69, 89, 11, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[44, 91, 83, 60],
       [20, 46, 95,  5],
       [53, 21, 61, 38],
       [94, 85, 80, 18],
       [ 4,  8, 37, 51],
       [41,  1, 42, 77]])

In [4]:
np.sort(b)

array([[44, 60, 83, 91],
       [ 5, 20, 46, 95],
       [21, 38, 53, 61],
       [18, 80, 85, 94],
       [ 4,  8, 37, 51],
       [ 1, 41, 42, 77]])

In [5]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a4.sort(axis=0)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.sort(a4)[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [8]:
np.sort(b)[::-1]

array([[ 1, 41, 42, 77],
       [ 4,  8, 37, 51],
       [18, 80, 85, 94],
       [21, 38, 53, 61],
       [ 5, 20, 46, 95],
       [44, 60, 83, 91]])

In [9]:
np.sort(b,axis=1)

array([[44, 60, 83, 91],
       [ 5, 20, 46, 95],
       [21, 38, 53, 61],
       [18, 80, 85, 94],
       [ 4,  8, 37, 51],
       [ 1, 41, 42, 77]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [10]:
# code
np.append(a,200)

array([ 58,  80,  69,  89,  11,  86,  75,  90,  13,  16,  75,  86,  61,
         4,  79, 200])

In [11]:
b

array([[44, 91, 83, 60],
       [20, 46, 95,  5],
       [53, 21, 61, 38],
       [94, 85, 80, 18],
       [ 4,  8, 37, 51],
       [41,  1, 42, 77]])

In [12]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[44., 91., 83., 60.,  1.],
       [20., 46., 95.,  5.,  1.],
       [53., 21., 61., 38.,  1.],
       [94., 85., 80., 18.,  1.],
       [ 4.,  8., 37., 51.,  1.],
       [41.,  1., 42., 77.,  1.]])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[44.        , 91.        , 83.        , 60.        ,  0.56190909],
       [20.        , 46.        , 95.        ,  5.        ,  0.38645944],
       [53.        , 21.        , 61.        , 38.        ,  0.71564509],
       [94.        , 85.        , 80.        , 18.        ,  0.88837635],
       [ 4.        ,  8.        , 37.        , 51.        ,  0.85744902],
       [41.        ,  1.        , 42.        , 77.        ,  0.38671764]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [14]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [17]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [18]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [21]:
np.expand_dims(a,axis=1)

array([[58],
       [80],
       [69],
       [89],
       [11],
       [86],
       [75],
       [90],
       [13],
       [16],
       [75],
       [86],
       [61],
       [ 4],
       [79]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
a

array([58, 80, 69, 89, 11, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

In [23]:
p = np.array([ 9, 56, 77, 51, 74, 32, 32, 88, 99, 98, 70, 30, 95,  8, 61])

In [24]:
p[np.where(p>50)]

array([56, 77, 51, 74, 88, 99, 98, 70, 95, 61])

In [25]:
# find all indices with value greater than 50
a[np.where(a>50)]

array([58, 80, 69, 89, 86, 75, 90, 75, 86, 61, 79])

In [26]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0,  0, 11,  0,  0,  0, 13, 16,  0,  0,  0,  4,  0])

In [27]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 69, 89, 11,  0, 75,  0, 13,  0, 75,  0, 61,  0, 79])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [28]:
# code
a

array([58, 80, 69, 89, 11, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

In [29]:
a[1]

80

In [30]:
np.argmax(a)

7

In [31]:
b

array([[44, 91, 83, 60],
       [20, 46, 95,  5],
       [53, 21, 61, 38],
       [94, 85, 80, 18],
       [ 4,  8, 37, 51],
       [41,  1, 42, 77]])

In [32]:
np.argmax(b,axis=0)

array([3, 0, 1, 5], dtype=int64)

In [33]:
np.argmax(b,axis=1)

array([1, 2, 2, 0, 3, 3], dtype=int64)

In [34]:
# np.argmin
np.argmin(a)

13

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [35]:
a

array([58, 80, 69, 89, 11, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

In [36]:
np.cumsum(a)

array([ 58, 138, 207, 296, 307, 393, 468, 558, 571, 587, 662, 748, 809,
       813, 892])

In [37]:
b

array([[44, 91, 83, 60],
       [20, 46, 95,  5],
       [53, 21, 61, 38],
       [94, 85, 80, 18],
       [ 4,  8, 37, 51],
       [41,  1, 42, 77]])

In [38]:
np.cumsum(b,axis=1)

array([[ 44, 135, 218, 278],
       [ 20,  66, 161, 166],
       [ 53,  74, 135, 173],
       [ 94, 179, 259, 277],
       [  4,  12,  49, 100],
       [ 41,  42,  84, 161]])

In [39]:
np.cumsum(b)

array([  44,  135,  218,  278,  298,  344,  439,  444,  497,  518,  579,
        617,  711,  796,  876,  894,  898,  906,  943,  994, 1035, 1036,
       1078, 1155])

In [40]:
# np.cumprod
np.cumprod(a)

array([         58,        4640,      320160,    28494240,   313436640,
        1185747264, -1263268416, -2025007744,  -555296896,  -294815744,
        -636344320,  1108963328, -1072713728,     4112384,   324878336])

In [41]:
a

array([58, 80, 69, 89, 11, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [42]:
p

array([ 9, 56, 77, 51, 74, 32, 32, 88, 99, 98, 70, 30, 95,  8, 61])

In [71]:
np.percentile(p,80)

98.2

In [44]:
np.median(p)

61.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [45]:
# code
p

array([ 9, 56, 77, 51, 74, 32, 32, 88, 99, 98, 70, 30, 95,  8, 61])

In [46]:
np.histogram(p,bins=[0,30 , 50,100])

(array([ 2,  3, 10], dtype=int64), array([  0,  30,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [48]:
# code
p


array([ 9, 56, 77, 51, 74, 32, 32, 88, 99, 98, 70, 30, 95,  8, 61])

In [49]:
items = [10,20,30,40,50,60,70,80,90,100]

p[np.isin(p,items)]

array([70, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [50]:
# code
p

array([ 9, 56, 77, 51, 74, 32, 32, 88, 99, 98, 70, 30, 95,  8, 61])

In [51]:
np.flip(p)

array([61,  8, 95, 30, 70, 98, 99, 88, 32, 32, 74, 51, 77, 56,  9])

In [52]:
b

array([[44, 91, 83, 60],
       [20, 46, 95,  5],
       [53, 21, 61, 38],
       [94, 85, 80, 18],
       [ 4,  8, 37, 51],
       [41,  1, 42, 77]])

In [53]:
np.flip(b,axis=1)

array([[60, 83, 91, 44],
       [ 5, 95, 46, 20],
       [38, 61, 21, 53],
       [18, 80, 85, 94],
       [51, 37,  8,  4],
       [77, 42,  1, 41]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [54]:
# code
p

array([ 9, 56, 77, 51, 74, 32, 32, 88, 99, 98, 70, 30, 95,  8, 61])

In [55]:
np.put(p,[0,1],[110,530])

In [56]:
p

array([110, 530,  77,  51,  74,  32,  32,  88,  99,  98,  70,  30,  95,
         8,  61])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [57]:
# code
a

array([58, 80, 69, 89, 11, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

In [58]:
np.delete(a,[0,2,4])

array([80, 89, 86, 75, 90, 13, 16, 75, 86, 61,  4, 79])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [59]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.intersect1d(m,n)

array([3, 4, 5])

In [61]:
np.setdiff1d(n,m)

array([6, 7])

In [62]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [63]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [64]:
# code
p

array([110, 530,  77,  51,  74,  32,  32,  88,  99,  98,  70,  30,  95,
         8,  61])

In [65]:
np.clip(p,a_min=25,a_max=75)

array([75, 75, 75, 51, 74, 32, 32, 75, 75, 75, 70, 30, 75, 25, 61])

# NumPy ufuncs

# What is Vectorization?
    # Converting iterative statements into a vector based operation is called vectorization.

    # It is faster as modern CPUs are optimized for such operations.

In [66]:
# Without ufunc, we can use Python's built-in zip() method:

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [67]:
import numpy as np

x = [1, 2, 3, 4]
y = [5, 6, 7 ,8]
z = np.add(x, y)

print(z)

[ 6  8 10 12]


How To Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.

In [68]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)  # 2 - passing from input and 
                                    # 1 - final output

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

myadd

[6 8 10 12]


<ufunc 'myadd (vectorized)'>

In [69]:
print(type(np.add))

<class 'numpy.ufunc'>
